---
author: "Tom Palmer"
date: "`r format(Sys.time(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction {.unnumbered}

The following is intended as a set of tips for people learning how to use Git and GitHub.

## Session plan

- Introduction
- Tips
- Short practical on making a pull request
- Elsie - the OpenSAFELY codelist system

## Session aims

By the end of the session you should 

- have a basic understanding of how Git works
- be able to perform common Git operations using GitHub Desktop and the GitHub web interface, including  
  - clone a repo from GitHub
  - make a new branch
  - make commits
  - push your branch to GitHub
  - make a pull request

## Guides to Git and GitHub

There are many excellent guides to Git and GitHub online, e.g.,

-	Intro to GitHub [here](https://guides.github.com/activities/hello-world/)
- GitHub Training & Guides YouTube channel [here](https://www.youtube.com/githubguides)
- Git documentation and training [here](https://git-scm.com/doc)
- Hadley Wickham on Git [here](https://r-pkgs.org/git.html)
- Jenny Bryan on Git and GitHub with R [here](https://happygitwithr.com/)

And most relevantly the OpenSAFELY documentation [here](https://docs.opensafely.org/getting-started/).
